name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Appium globally
        run: npm install -g appium

      - name: Install UiAutomator2 driver
        run: appium driver install uiautomator2

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          emulator-options: "-no-window -gpu swiftshader_indirect -noaudio"
          script: echo "Emulator started"

      - name: Wait for emulator to boot
        run: |
          echo "Waiting for emulator to finish booting..."
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            sleep 5
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "boot_completed = $boot_completed"
          done
          echo "✅ Emulator is fully booted."

      - name: Run Appium server (in background)
        run: |
           nohup appium --port 4725 > appium.log 2>&1 &

      - name: Wait for Appium to start
        run: sleep 10

      - name: Run tests
        run: node test3.js
