name: Appium Tests (macOS)

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Appium and UiAutomator2 driver
        run: |
          npm install -g appium@v2.18.0
          echo "$(npm bin -g)" >> $GITHUB_PATH
          appium -v
          appium driver install uiautomator2

      - name: Create and start Android Emulator
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;google_apis;x86_64"
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-31;google_apis;x86_64" -d pixel
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-window -no-audio -no-snapshot -no-boot-anim -gpu swiftshader_indirect &
          adb wait-for-device
      
      - name: Wait for emulator to boot
        run: |
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          echo "Waiting for emulator to finish booting..."
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            sleep 10
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "boot_completed = $boot_completed"
          done
          echo "✅ Emulator is fully booted."

      - name: Run Appium server (in background)
        run: |
          nohup appium --port 4725 > appium.log 2>&1 &

      - name: Wait for Appium to start
        run: sleep 10

      - name: Run tests
        run: node test3.js
