name: Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Appium and UiAutomator2 driver
        run: |
          npm install -g appium@v2.18.0
          echo "$(npm bin -g)" >> $GITHUB_PATH
          appium -v
          appium driver install uiautomator2

      - name: Set up and start Android emulator
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator" "system-images;android-31;google_apis;x86_64"
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools
          echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-31;google_apis;x86_64" -d pixel --force
          # Start emulator
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-snapshot -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect > /dev/null 2>&1 &

      - name: List available AVDs
        run: |
          ls -l $HOME/.android/avd
          avdmanager list avd

      - name: Wait for emulator to boot
        run: |
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          echo "Waiting for emulator to boot..."
          until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
            sleep 10
            echo "Still waiting..."
          done
          echo "✅ Emulator booted"

      - name: Start Appium Server
        run: |
          nohup appium --port 4723 > appium.log 2>&1 &

      - name: Wait for Appium
        run: sleep 10

      - name: Run tests
        run: node test3.js
