name: Android Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: default
          arch: x86_64

      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64"

      - name: Start emulator
        run: |
          adb start-server
          emulator -avd test -no-snapshot -no-audio -no-window &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: node test3.js
