name: Appium Tests (macOS)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Adjust this if you're using macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Android SDK
        run: |
          # Set up Android SDK environment variables
          echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV
          
          # Install Android SDK and tools
          mkdir -p $ANDROID_HOME
          curl -s https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -o commandlinetools.zip
          unzip commandlinetools.zip -d $ANDROID_HOME
          rm commandlinetools.zip
          
          # Install SDK components
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-31;google_apis;x86_64"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Appium and UiAutomator2 driver
        run: |
          npm install -g appium@v2.18.0
          echo "$(npm bin -g)" >> $GITHUB_PATH
          appium -v
          appium driver install uiautomator2

      - name: Create and start Android Emulator
        run: |
          # Create AVD with the new name "myNewEmulator"
          $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n myNewEmulator -k "system-images;android-31;google_apis;x86_64" -d pixel

          # Start the emulator using the new AVD name "myNewEmulator"
          $ANDROID_HOME/emulator/emulator -avd myNewEmulator -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -no-snapshot-save &

      - name: Wait for emulator to boot
        run: |
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          echo "Waiting for emulator to finish booting..."
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            sleep 10
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "boot_completed = $boot_completed"
          done
          echo "✅ Emulator is fully booted."

      - name: Run Appium server (in background)
        run: |
          nohup appium --port 4725 > appium.log 2>&1 &

      - name: Wait for Appium to start
        run: sleep 10

      - name: Run tests
        run: node test3.js
