name: Run iOS Script on Emulator

on:
  push:
    branches: 
        - 'testBranch'
  workflow_dispatch:

jobs:
  run-on-emulator:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or the version you need

      - name: Install dependencies
        run: npm install

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Boot iOS Simulator
        run: |
            xcrun simctl list devices
            SIMULATOR_ID=$(xcrun simctl list devices | \
            grep -m 1 "iPhone 15 Pro" | \
            grep -oE '[A-F0-9\-]{36}')
            echo "Booting simulator with UDID: $SIMULATOR_ID"
            xcrun simctl boot "$SIMULATOR_ID"
            xcrun simctl bootstatus "$SIMULATOR_ID" -b

      - name: Run JS Script
        run: |
          node test3.js